version: '3.3'
services:
  proxy:
    build: nginx/.
    networks:
    - frontend
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - certs:/etc/nginx/certs
    - nginx-config:/etc/nginx/conf.d
    - nginx-vhosts:/etc/nginx/vhost.d
    - nginx-webroot:/usr/share/nginx/html
    labels:
    - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    hostname: proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:stable
    volumes:
    - certs:/etc/nginx/certs
    - nginx-config:/etc/nginx/conf.d
    - nginx-vhosts:/etc/nginx/vhost.d
    - nginx-webroot:/usr/share/nginx/html
    - /var/run/docker.sock:/var/run/docker.sock:ro
    hostname: letsencrypt
  nexus:
    image: sonatype/nexus3:3.15.2
    networks:
    - frontend
    environment:
    - VIRTUAL_HOST=nexus.4digi.ru
    - VIRTUAL_PORT=8081
    - LETSENCRYPT_HOST=nexus.4digi.ru
    - LETSENCRYPT_EMAIL=dim777@ya.ru
    volumes:
    - /opt/docker/nexus-data:/nexus-data
    hostname: nexus
  carsclinicru:
    build: php_apache/.
    networks:
    - frontend
    ports:
      - "8093:80"
    volumes:
    - /opt/www/carsclinic.ru/data/public:/var/www/html
    - /opt/www/carsclinic.ru/apache:/etc/apache2/sites-available
    hostname: carsclinicru
  inebru:
    build: php_apache/.
    networks:
      - frontend
    #ports:
    #  - "8091:80"
    environment:
      - VIRTUAL_HOST=ineb.ru, www.ineb.ru
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=ineb.ru
      - LETSENCRYPT_EMAIL=dim777@ya.ru
    volumes:
      - /opt/www/ineb.ru/data/public:/var/www/html
      - /opt/www/ineb.ru/apache:/etc/apache2/sites-available
    hostname: inebru
  mysql:
    image: mysql:5.7.22
    networks:
    - frontend
    ports:
    - "13306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
    volumes:
    - /opt/docker/mysql_data:/var/lib/mysql
    hostname: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    networks:
    - frontend
    ports:
    - "8092:80"
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_PASS}
    - PMA_HOST=mysql
    hostname: phpmyadmin
volumes:
  certs:
  nginx-config:
  nginx-vhosts:
  nginx-webroot:
networks:
  frontend: